# Generated by Django 5.2.8 on 2026-04-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_messagebroadcast_level_messagedelivery_is_read_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsletterSubscriber",
        ),
    ]
