# Generated by Django 5.2.14 on 2026-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_enabled', models.BooleanField(default=True)),
                ('min_supported_version', models.CharField(default='1.0.0', max_length=32)),
                ('min_supported_build', models.PositiveIntegerField(default=1)),
                ('force_update', models.BooleanField(default=False)),
                ('message', models.TextField(default='هذه النسخة التجريبية انتهت. فضلاً حمّل النسخة الجديدة.')),
                ('update_url', models.URLField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile app config',
                'verbose_name_plural': 'Mobile app config',
            },
        ),
    ]
