# Generated by Django 5.2.14 on 2026-07-18 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedMobileAppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], db_index=True, max_length=16, verbose_name='المنصة')),
                ('version_name', models.CharField(blank=True, default='', max_length=32)),
                ('build_number', models.PositiveIntegerField(verbose_name='رقم البناء')),
                ('reason_ar', models.TextField(blank=True, default='')),
                ('reason_en', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocked_mobile_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إصدار محظور',
                'verbose_name_plural': 'الإصدارات المحظورة',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'build_number'), name='uniq_blocked_mobile_platform_build')],
            },
        ),
        migrations.CreateModel(
            name='MobileAppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], db_index=True, max_length=16, verbose_name='المنصة')),
                ('version_name', models.CharField(max_length=32, verbose_name='رقم الإصدار')),
                ('build_number', models.PositiveIntegerField(verbose_name='رقم البناء')),
                ('minimum_version_name', models.CharField(blank=True, default='', max_length=32, verbose_name='أقل إصدار مدعوم')),
                ('minimum_build_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='أقل رقم بناء مدعوم')),
                ('update_mode', models.CharField(choices=[('none', 'بدون تحديث'), ('optional', 'تحديث اختياري'), ('required', 'تحديث إجباري')], default='none', max_length=16, verbose_name='نوع التحديث')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='نشط')),
                ('update_title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('update_title_en', models.CharField(blank=True, default='', max_length=255)),
                ('update_message_ar', models.TextField(blank=True, default='')),
                ('update_message_en', models.TextField(blank=True, default='')),
                ('release_notes_ar', models.TextField(blank=True, default='')),
                ('release_notes_en', models.TextField(blank=True, default='')),
                ('store_url', models.URLField(blank=True, default='', max_length=500)),
                ('allow_later', models.BooleanField(default=True, verbose_name='السماح بالتأجيل')),
                ('later_reminder_hours', models.PositiveIntegerField(blank=True, default=24, null=True, verbose_name='ساعات إعادة التذكير')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء التطبيق')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mobile_app_versions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mobile_app_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إصدار تطبيق',
                'verbose_name_plural': 'إصدارات التطبيق',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['platform', 'is_active'], name='mobile_mobi_platfor_fbb804_idx'), models.Index(fields=['platform', '-build_number'], name='mobile_mobi_platfor_e93f0f_idx')],
            },
        ),
    ]
