from django.shortcuts import redirect
from django.urls import path

from .views import (
    announcement_create,
    announcement_delete,
    announcement_detail,
    announcement_list,
    announcement_toggle_active,
    announcement_update,
    appointment_all_list,
    appointment_detail,
    appointment_overview,
    app_notification_create,
    app_notification_delete,
    app_notification_detail,
    app_notification_list,
    app_notification_toggle_active,
    app_notification_update,
    blocked_mobile_version_create,
    blocked_mobile_version_list,
    blocked_mobile_version_toggle_active,
    blocked_mobile_version_update,
    call_recording_playback_url,
    call_session_detail,
    call_session_list,
    call_session_ratings_detail,
    dashboard_user_student_detail,
    dashboard_user_student_profile_image,
    dashboard_user_teacher_detail,
    dashboard_user_teacher_ijazah,
    dashboard_user_teacher_profile_image,
    dashboard_users_list,
    dashboard,
    home,
    overview,
    subscription_plan_create,
    subscription_plan_delete,
    subscription_plan_list,
    subscription_plan_toggle_active,
    subscription_plan_update,
    student_subscription_balance_update,
    student_subscription_delete,
    student_subscription_detail,
    student_subscription_list,
    student_subscription_update,
    teacher_availability_list,
    session_evaluation_list,
    rating_question_create,
    rating_question_update,
    rating_question_delete,
    rating_category_toggle,
    call_recording_delete,
    call_recording_list,
    mobile_app_config_settings,
    mobile_version_activate,
    mobile_version_create,
    mobile_version_deactivate,
    mobile_version_detail,
    mobile_version_list,
    mobile_version_update,
)

app_name = "dashboard"


urlpatterns = [
    path("", lambda request: redirect("dashboard:home_dashboard")),
    path("home/", home, name="home_dashboard"),
    path("manage/", dashboard, name="manage"),
    path("dashboard/", home, name="home"),
    path("overview_dashboard/", overview, name="overview_dashboard"),
    path("subscription-plans/", subscription_plan_list, name="subscription_plan_list"),
    path(
        "subscription-plans/create/",
        subscription_plan_create,
        name="subscription_plan_create",
    ),
    path(
        "subscription-plans/<int:pk>/edit/",
        subscription_plan_update,
        name="subscription_plan_update",
    ),
    path(
        "subscription-plans/<int:pk>/delete/",
        subscription_plan_delete,
        name="subscription_plan_delete",
    ),
    path(
        "subscription-plans/<int:pk>/toggle-active/",
        subscription_plan_toggle_active,
        name="subscription_plan_toggle_active",
    ),
    path("subscriptions/", student_subscription_list, name="student_subscription_list"),
    path(
        "subscriptions/user/<int:user_id>/",
        student_subscription_detail,
        name="student_subscription_detail",
    ),
    path(
        "subscriptions/user/<int:user_id>/balance/edit/",
        student_subscription_balance_update,
        name="student_subscription_balance_update",
    ),
    path(
        "subscriptions/<int:pk>/edit/",
        student_subscription_update,
        name="student_subscription_update",
    ),
    path(
        "subscriptions/<int:pk>/delete/",
        student_subscription_delete,
        name="student_subscription_delete",
    ),
    path("app-notifications/", app_notification_list, name="app_notification_list"),
    path(
        "app-notifications/create/",
        app_notification_create,
        name="app_notification_create",
    ),
    path(
        "app-notifications/<int:pk>/",
        app_notification_detail,
        name="app_notification_detail",
    ),
    path(
        "app-notifications/<int:pk>/edit/",
        app_notification_update,
        name="app_notification_update",
    ),
    path(
        "app-notifications/<int:pk>/delete/",
        app_notification_delete,
        name="app_notification_delete",
    ),
    path(
        "app-notifications/<int:pk>/toggle-active/",
        app_notification_toggle_active,
        name="app_notification_toggle_active",
    ),
    path("announcements/", announcement_list, name="announcement_list"),
    path("announcements/create/", announcement_create, name="announcement_create"),
    path(
        "announcements/<int:pk>/",
        announcement_detail,
        name="announcement_detail",
    ),
    path("announcements/<int:pk>/edit/", announcement_update, name="announcement_update"),
    path("announcements/<int:pk>/delete/", announcement_delete, name="announcement_delete"),
    path(
        "announcements/<int:pk>/toggle-active/",
        announcement_toggle_active,
        name="announcement_toggle_active",
    ),
    path("appointments/", appointment_overview, name="appointment_overview"),
    path("appointments/all/", appointment_all_list, name="appointment_all_list"),
    path("appointments/<int:pk>/", appointment_detail, name="appointment_detail"),
    path("users/", dashboard_users_list, name="dashboard_users_list"),
    path(
        "users/teachers/<int:user_id>/",
        dashboard_user_teacher_detail,
        name="dashboard_user_teacher_detail",
    ),
    path(
        "users/students/<int:user_id>/",
        dashboard_user_student_detail,
        name="dashboard_user_student_detail",
    ),
    path(
        "users/teachers/<int:user_id>/profile-image/",
        dashboard_user_teacher_profile_image,
        name="dashboard_user_teacher_profile_image",
    ),
    path(
        "users/teachers/<int:user_id>/ijazah/",
        dashboard_user_teacher_ijazah,
        name="dashboard_user_teacher_ijazah",
    ),
    path(
        "users/students/<int:user_id>/profile-image/",
        dashboard_user_student_profile_image,
        name="dashboard_user_student_profile_image",
    ),
    path("calls/", call_session_list, name="call_session_list"),
    path(
        "calls/recordings/<int:pk>/playback-url/",
        call_recording_playback_url,
        name="call_recording_playback_url",
    ),
    path(
        "calls/sessions/<int:session_id>/ratings/",
        call_session_ratings_detail,
        name="call_session_ratings_detail",
    ),
    path(
        "calls/sessions/<int:session_id>/",
        call_session_detail,
        name="call_session_detail",
    ),
    path(
        "teachers/availability/",
        teacher_availability_list,
        name="teacher_availability_list",
    ),
    path("evaluations/", session_evaluation_list, name="session_evaluation_list"),
    path(
        "evaluations/questions/add/",
        rating_question_create,
        name="rating_question_create",
    ),
    path(
        "evaluations/questions/<int:pk>/edit/",
        rating_question_update,
        name="rating_question_update",
    ),
    path(
        "evaluations/questions/<int:pk>/delete/",
        rating_question_delete,
        name="rating_question_delete",
    ),
    path(
        "evaluations/categories/<str:category>/toggle/",
        rating_category_toggle,
        name="rating_category_toggle",
    ),
    path("recordings/", call_recording_list, name="call_recording_list"),
    path(
        "recordings/<int:pk>/delete/",
        call_recording_delete,
        name="call_recording_delete",
    ),
    path(
        "mobile-app-config/",
        mobile_app_config_settings,
        name="mobile_app_config_settings",
    ),
    path("mobile-versions/", mobile_version_list, name="mobile_version_list"),
    path(
        "mobile-versions/create/",
        mobile_version_create,
        name="mobile_version_create",
    ),
    path(
        "mobile-versions/<int:pk>/",
        mobile_version_detail,
        name="mobile_version_detail",
    ),
    path(
        "mobile-versions/<int:pk>/edit/",
        mobile_version_update,
        name="mobile_version_update",
    ),
    path(
        "mobile-versions/<int:pk>/activate/",
        mobile_version_activate,
        name="mobile_version_activate",
    ),
    path(
        "mobile-versions/<int:pk>/deactivate/",
        mobile_version_deactivate,
        name="mobile_version_deactivate",
    ),
    path(
        "mobile-versions/blocked/",
        blocked_mobile_version_list,
        name="blocked_mobile_version_list",
    ),
    path(
        "mobile-versions/blocked/create/",
        blocked_mobile_version_create,
        name="blocked_mobile_version_create",
    ),
    path(
        "mobile-versions/blocked/<int:pk>/edit/",
        blocked_mobile_version_update,
        name="blocked_mobile_version_update",
    ),
    path(
        "mobile-versions/blocked/<int:pk>/toggle-active/",
        blocked_mobile_version_toggle_active,
        name="blocked_mobile_version_toggle_active",
    ),
]
