# Generated by Django 5.2.8 on 2026-03-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديدة"),
                            ("read", "تمت القراءة"),
                            ("replied", "تم الرد"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="contact_con_status_fa3e24_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="contact_con_created_fddb83_idx"
                    ),
                ],
            },
        ),
    ]
