# Generated by Django 5.2.14 on 2026-05-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_reply_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='source',
            field=models.CharField(choices=[('web', 'موقع الويب'), ('app', 'تطبيق جوال')], default='web', max_length=10),
        ),
    ]
