# Generated by Django 5.2.8 on 2026-03-21 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Qurra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(db_index=True, unique=True),
                ),
                ("name_ar", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("fullname", models.CharField(max_length=255)),
                ("info", models.TextField()),
                ("image", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Surah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surah_number",
                    models.PositiveSmallIntegerField(db_index=True, unique=True),
                ),
                ("surah_name_ar", models.CharField(max_length=100)),
                ("surah_name_en", models.CharField(blank=True, max_length=100)),
                ("page_start", models.PositiveSmallIntegerField(db_index=True)),
                ("page_end", models.PositiveSmallIntegerField(db_index=True)),
                ("ayah_count", models.PositiveSmallIntegerField()),
                (
                    "revelation_type",
                    models.CharField(
                        choices=[("meccan", "مكية"), ("medinan", "مدنية")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["surah_number"],
                "indexes": [
                    models.Index(
                        fields=["page_start", "page_end"],
                        name="quran_surah_page_st_044de3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ayah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surah_number", models.PositiveSmallIntegerField(db_index=True)),
                ("ayah_number", models.PositiveSmallIntegerField(db_index=True)),
                ("page_number", models.PositiveSmallIntegerField(db_index=True)),
                ("juz_number", models.PositiveSmallIntegerField(db_index=True)),
                ("text", models.TextField()),
                (
                    "surah",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ayat",
                        to="quran.surah",
                    ),
                ),
            ],
            options={
                "ordering": ["surah_number", "ayah_number"],
            },
        ),
        migrations.CreateModel(
            name="TafsirBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("lang", models.CharField(max_length=100)),
                ("api", models.CharField(max_length=100)),
                ("image", models.CharField(blank=True, max_length=255)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("info", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(db_index=True, default=1),
                ),
            ],
            options={
                "ordering": ["sort_order", "number"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="quran_tafsi_is_acti_328085_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Tafsir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surah_id", models.PositiveSmallIntegerField(db_index=True)),
                ("ayah_number", models.PositiveSmallIntegerField(db_index=True)),
                ("text", models.TextField()),
                (
                    "ayah",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tafaseer",
                        to="quran.ayah",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tafaseer",
                        to="quran.tafsirbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AyahPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surah_number", models.SmallIntegerField(db_index=True)),
                ("ayah_number", models.SmallIntegerField(db_index=True)),
                ("page_number", models.SmallIntegerField(db_index=True)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("polygon", models.JSONField(blank=True, null=True)),
                (
                    "ayah",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="quran.ayah",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number", "surah_number", "ayah_number"],
                "indexes": [
                    models.Index(
                        fields=["page_number"], name="quran_ayahp_page_nu_8c6b15_idx"
                    ),
                    models.Index(
                        fields=["surah_number", "ayah_number"],
                        name="quran_ayahp_surah_n_4c226d_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="ayah",
            index=models.Index(
                fields=["surah_number", "ayah_number"],
                name="quran_ayah_surah_n_8dd501_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ayah",
            index=models.Index(
                fields=["page_number"], name="quran_ayah_page_nu_df7d1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ayah",
            index=models.Index(
                fields=["juz_number"], name="quran_ayah_juz_num_6cc408_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ayah",
            unique_together={("surah_number", "ayah_number")},
        ),
        migrations.AddIndex(
            model_name="tafsir",
            index=models.Index(
                fields=["book", "surah_id", "ayah_number"],
                name="quran_tafsi_book_id_b4842c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tafsir",
            index=models.Index(
                fields=["book", "ayah"], name="quran_tafsi_book_id_081a85_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tafsir",
            unique_together={("book", "surah_id", "ayah_number")},
        ),
    ]
