# Generated by Django 5.2.8 on 2026-04-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ayahposition",
            name="ayah_number",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
    ]
