# Generated by Django 5.2.8 on 2026-04-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0004_add_mushaf_key_to_ayahposition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ayahposition",
            options={
                "ordering": ["mushaf_key", "page_number", "surah_number", "ayah_number"]
            },
        ),
        migrations.RenameIndex(
            model_name="ayahposition",
            new_name="quran_ayahp_mushaf__ed98fb_idx",
            old_name="quran_ayahp_mushaf__a7dc2f_idx",
        ),
        migrations.RenameIndex(
            model_name="ayahposition",
            new_name="quran_ayahp_mushaf__a8fa7b_idx",
            old_name="quran_ayahp_mushaf__2c8eab_idx",
        ),
    ]
