# Generated by Django 5.2.8 on 2026-04-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0005_alter_ayahposition_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AyahWordMeaning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surah_number", models.PositiveSmallIntegerField(db_index=True)),
                ("ayah_number", models.PositiveSmallIntegerField(db_index=True)),
                ("word", models.CharField(max_length=255)),
                ("word_plain", models.CharField(blank=True, max_length=255)),
                ("meaning", models.TextField()),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(db_index=True, default=1),
                ),
                (
                    "ayah",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_meanings",
                        to="quran.ayah",
                    ),
                ),
            ],
            options={
                "ordering": ["surah_number", "ayah_number", "sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["surah_number", "ayah_number"],
                        name="quran_ayahw_surah_n_fe9907_idx",
                    ),
                    models.Index(
                        fields=["ayah"], name="quran_ayahw_ayah_id_0df592_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("surah_number", "ayah_number", "sort_order"),
                        name="unique_word_meaning_order_per_ayah",
                    )
                ],
            },
        ),
    ]
