# Generated by Django 5.2.8 on 2026-04-13 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0006_ayahwordmeaning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wird_number", models.PositiveIntegerField(default=1)),
                ("start_surah_number", models.PositiveSmallIntegerField()),
                ("start_ayah_number", models.PositiveSmallIntegerField()),
                ("end_surah_number", models.PositiveSmallIntegerField()),
                ("end_ayah_number", models.PositiveSmallIntegerField()),
                ("start_page", models.PositiveSmallIntegerField()),
                ("end_page", models.PositiveSmallIntegerField()),
                (
                    "current_page",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
