# Generated by Django 5.2.8 on 2026-04-13 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0007_dailyreading"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KhatmaProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("khatma_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "start_mode",
                    models.CharField(
                        choices=[("beginning", "Beginning of Mushaf")],
                        default="beginning",
                        max_length=30,
                    ),
                ),
                ("duration_days", models.PositiveSmallIntegerField(default=30)),
                (
                    "daily_amount_type",
                    models.CharField(
                        choices=[("juz", "Juz")], default="juz", max_length=20
                    ),
                ),
                ("daily_amount_value", models.PositiveSmallIntegerField(default=1)),
                ("current_wird_number", models.PositiveSmallIntegerField(default=1)),
                ("total_wirds", models.PositiveSmallIntegerField(default=30)),
                (
                    "current_wird_start_page",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("current_wird_end_page", models.PositiveSmallIntegerField(default=21)),
                ("current_page", models.PositiveSmallIntegerField(default=1)),
                ("start_surah_number", models.PositiveSmallIntegerField(default=1)),
                ("start_ayah_number", models.PositiveSmallIntegerField(default=1)),
                ("end_surah_number", models.PositiveSmallIntegerField(default=2)),
                ("end_ayah_number", models.PositiveSmallIntegerField(default=141)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="khatma_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Khatma Progress",
                "verbose_name_plural": "Khatma Progress",
            },
        ),
        migrations.DeleteModel(
            name="DailyReading",
        ),
    ]
