# Generated by Django 5.2.14 on 2026-05-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0010_rename_quran_audio_created_9d07a0_idx_quran_audio_created_851cef_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyahTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.PositiveSmallIntegerField(db_index=True)),
                ('ayah_number', models.PositiveSmallIntegerField(db_index=True)),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('translation', models.TextField()),
            ],
            options={
                'ordering': ['surah_number', 'ayah_number'],
                'indexes': [models.Index(fields=['language'], name='quran_ayaht_languag_0f7d8e_idx'), models.Index(fields=['surah_number', 'ayah_number'], name='quran_ayaht_surah_n_41c899_idx'), models.Index(fields=['language', 'surah_number'], name='quran_ayaht_languag_498d6e_idx')],
                'constraints': [models.UniqueConstraint(fields=('surah_number', 'ayah_number', 'language'), name='unique_ayah_translation')],
            },
        ),
    ]
