# Generated by Django 5.2.14 on 2026-05-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0014_fix_ayah_juz_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatmaprogress',
            name='tracking_mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
    ]
