# Generated by Django 5.2.8 on 2026-04-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationcampaign",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="campaigns/"),
        ),
    ]
