# Generated by Django 5.2.8 on 2026-04-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_communicationcampaign_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communicationcampaignchannel",
            name="channel",
            field=models.CharField(
                choices=[
                    ("x", "منصة X"),
                    ("facebook", "فيسبوك"),
                    ("telegram_group", "تيليجرام - قروب"),
                    ("telegram_channel", "تيليجرام - قناة"),
                ],
                max_length=30,
            ),
        ),
    ]
