# Generated by Django 5.2.14 on 2026-05-28 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('daily_wird', 'الورد اليومي'), ('morning_adhkar', 'أذكار الصباح'), ('evening_adhkar', 'أذكار المساء'), ('kahf_friday', 'سورة الكهف - الجمعة')], max_length=30)),
                ('is_enabled', models.BooleanField(default=False)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reminder_type'],
                'unique_together': {('user', 'reminder_type')},
            },
        ),
    ]
