# Generated by Django 5.2.14 on 2026-05-31 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_teacheravailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_teachers', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'معلّم مفضّل',
                'verbose_name_plural': 'المعلّمون المفضّلون',
                'constraints': [models.UniqueConstraint(fields=('student', 'teacher'), name='uniq_student_teacher_favorite')],
            },
        ),
    ]
