# Generated by Django 5.2.14 on 2026-06-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_teacherfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='ijazah',
            field=models.FileField(blank=True, help_text='Teacher Quran ijazah certificate', null=True, upload_to='teacher_ijazah/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='riwayat',
            field=models.TextField(blank=True, help_text='Quranic recitation traditions the teacher knows'),
        ),
    ]
