# Generated by Django 5.2.14 on 2026-06-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='auto_accept_calls',
            field=models.BooleanField(default=False, help_text='When true, student calls are accepted immediately without teacher action.'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_demo_teacher',
            field=models.BooleanField(default=False, help_text='Automated demo teacher for testing call flow (not a real human).'),
        ),
    ]
