# Generated by Django 5.2.14 on 2026-06-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_teacher_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Legacy flag; kept in sync with approval_status=approved.'),
        ),
    ]
