# Generated by Django 5.2.14 on 2026-06-07 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0009_rename_legacy_maqraa_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutoringsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tutoring session', 'verbose_name_plural': 'Tutoring sessions'},
        ),
        migrations.AlterField(
            model_name='tutoringsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions_as_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutoringsession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
