# Generated by Django 5.2.8 on 2026-05-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hifz", "0004_thematictopic_ayahthematicclassification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ayahthematicclassification",
            new_name="hifz_ayahth_surah_n_d2fec3_idx",
            old_name="hifz_ayaht_surah_n_6db53d_idx",
        ),
        migrations.RenameIndex(
            model_name="ayahthematicclassification",
            new_name="hifz_ayahth_surah_n_f3ffee_idx",
            old_name="hifz_ayaht_surah_n_b79c60_idx",
        ),
        migrations.RenameIndex(
            model_name="ayahthematicclassification",
            new_name="hifz_ayahth_topic_i_95561f_idx",
            old_name="hifz_ayaht_topic_i_8fbc4a_idx",
        ),
        migrations.RenameIndex(
            model_name="thematictopic",
            new_name="hifz_themat_color_i_a9e776_idx",
            old_name="hifz_themat_color_i_1c8158_idx",
        ),
        migrations.RenameIndex(
            model_name="thematictopic",
            new_name="hifz_themat_topic_i_81bb2d_idx",
            old_name="hifz_themat_topic_i_0f0987_idx",
        ),
    ]
