# Generated by Django 5.2.8 on 2026-04-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "ذكر"), ("female", "أنثى")],
                max_length=10,
                null=True,
            ),
        ),
    ]
