# Generated by Django 5.2.14 on 2026-05-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_communicationcampaignchannel_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='نص الإعلان')),
                ('announcement_type', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تنبيه'), ('urgent', 'عاجل'), ('event', 'فعالية')], default='info', max_length=20, verbose_name='نوع الإعلان')),
                ('announced_by', models.CharField(choices=[('admin', 'الإدارة'), ('supervisor', 'المشرف'), ('general_manager', 'المدير العام')], default='admin', max_length=32, verbose_name='من الإعلان')),
                ('target_type', models.CharField(choices=[('all', 'الجميع'), ('group', 'مجموعة')], default='all', max_length=20, verbose_name='لمن الإعلان')),
                ('target_group', models.CharField(blank=True, default='', max_length=255, verbose_name='المجموعة')),
                ('announcement_date', models.DateField(verbose_name='تاريخ الإعلان')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
