# Generated by Django 5.2.14 on 2026-05-30 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('audio', 'صوتي'), ('video', 'مرئي')], max_length=10, verbose_name='نوع الاتصال')),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('agora', 'Agora'), ('livekit', 'LiveKit'), ('jitsi', 'Jitsi'), ('webrtc', 'WebRTC')], default='mock', max_length=20, verbose_name='المزود')),
                ('room_name', models.CharField(blank=True, default='', max_length=128)),
                ('channel_name', models.CharField(blank=True, default='', max_length=128)),
                ('token', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('active', 'نشط'), ('ended', 'منتهي'), ('missed', 'فائت'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions_as_student', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions_as_teacher', to=settings.AUTH_USER_MODEL, verbose_name='المعلّم')),
            ],
            options={
                'verbose_name': 'جلسة اتصال',
                'verbose_name_plural': 'جلسات الاتصال',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
