# Generated by Django 5.2.14 on 2026-05-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='status',
            field=models.CharField(choices=[('pending', 'بانتظار المعلم'), ('active', 'نشط'), ('ended', 'منتهي'), ('rejected', 'مرفوض'), ('missed', 'لم يتم الرد'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
