# Generated by Django 5.2.14 on 2026-05-31 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_alter_callsession_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(max_length=10)),
                ('recording_url', models.URLField(blank=True, default='', max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('provider_recording_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='calls.callsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_recordings_as_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_recordings_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تسجيل مكالمة',
                'verbose_name_plural': 'تسجيلات المكالمات',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التقييم'), ('completed', 'تم التقييم')], default='pending', max_length=20)),
                ('focus_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pages_count', models.CharField(blank=True, default='', max_length=255)),
                ('surah', models.CharField(blank=True, default='', max_length=255)),
                ('memorization', models.TextField(blank=True, default='')),
                ('consolidation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='calls.callsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_evaluations_as_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_evaluations_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقييم جلسة',
                'verbose_name_plural': 'تقييمات الجلسات',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
