# Generated by Django 5.2.14 on 2026-06-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_callrecording_sessionevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='agora_resource_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='agora_sid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='recording_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='recording_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('starting', 'Starting'), ('recording', 'Recording'), ('stopping', 'Stopping'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='recording_uid',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
