# Generated by Django 5.2.14 on 2026-06-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_callrecording_cloud_recording_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecording',
            name='agora_resource_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='agora_sid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='provider_recording_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
