# Generated by Django 5.2.14 on 2026-06-07 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_drop_chat_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('teacher', 'تقييم المعلم'), ('student', 'تقييم الطالب'), ('demo_teacher', 'تقييم المعلم التجريبي')], max_length=20, verbose_name='نوع التقييم')),
                ('question_text', models.CharField(max_length=500, verbose_name='نص السؤال')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('max_stars', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سؤال تقييم',
                'verbose_name_plural': 'أسئلة التقييم',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CallPeerRatingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='calls.callpeerrating')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='calls.ratingquestion')),
            ],
            options={
                'verbose_name': 'إجابة تقييم',
                'verbose_name_plural': 'إجابات التقييم',
                'constraints': [models.UniqueConstraint(fields=('rating', 'question'), name='calls_callpeerratinganswer_unique_rating_question')],
            },
        ),
    ]
