# Generated by Django 5.2.14 on 2026-07-18 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0014_call_recording_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecordingConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_given', models.BooleanField(default=True)),
                ('consented_at', models.DateTimeField()),
                ('consent_version', models.CharField(default='recording-consent-v1', max_length=64)),
                ('platform', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_consents', to='calls.callsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_recording_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'موافقة تسجيل مكالمة',
                'verbose_name_plural': 'موافقات تسجيل المكالمات',
                'indexes': [models.Index(fields=['call_session', 'consent_given'], name='calls_callr_call_se_349395_idx')],
                'constraints': [models.UniqueConstraint(fields=('call_session', 'user'), name='uniq_call_recording_consent_user_session')],
            },
        ),
    ]
