# Generated by Django 5.2.14 on 2026-07-19 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0018_callsession_dual_media_ready_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='service_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('test_call', 'اتصال تجريبي')], db_index=True, default='', help_text='مثال: test_call — خدمة اتصال تجريبي بلا طرف معلّم.', max_length=32, verbose_name='نوع الخدمة المستقلة'),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_recordings_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='callsession',
            constraint=models.CheckConstraint(condition=models.Q(('teacher__isnull', False), ('is_test_call', True), ('service_type', 'test_call'), _connector='OR'), name='calls_callsession_teacher_required_unless_test'),
        ),
    ]
