# Generated by Django 5.2.8 on 2026-04-16 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hifz", "0001_initial"),
        ("quran", "0008_khatmaprogress_delete_dailyreading"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memorizedayah",
            options={"ordering": ["ayah__surah_number", "ayah__ayah_number"]},
        ),
        migrations.AddField(
            model_name="memorizedayah",
            name="last_revealed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memorizedayah",
            name="memorized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memorizedayah",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="memorizedayah",
            name="reveal_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="memorizedayah",
            name="ayah",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memorization_records",
                to="quran.ayah",
            ),
        ),
        migrations.AlterField(
            model_name="memorizedayah",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memorized_ayahs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
