# Generated by Django 5.2.14 on 2026-07-01 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('country_name', models.CharField(blank=True, max_length=128)),
                ('last_language', models.CharField(blank=True, max_length=16)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('hits_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os_name', models.CharField(blank=True, max_length=64)),
                ('os_version', models.CharField(blank=True, max_length=64)),
                ('browser_name', models.CharField(blank=True, max_length=64)),
                ('browser_version', models.CharField(blank=True, max_length=64)),
                ('device_type', models.CharField(blank=True, max_length=32)),
                ('last_language', models.CharField(blank=True, max_length=16)),
                ('client_source', models.CharField(blank=True, default='web', max_length=16)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('user_agent', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('visits_count', models.PositiveIntegerField(default=0)),
                ('total_active_seconds', models.PositiveIntegerField(default=0)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_flip', 'analytics_event_page_flip'), ('audio_play', 'analytics_event_audio_play'), ('audio_complete', 'analytics_event_audio_complete'), ('audio_pause', 'analytics_event_audio_pause'), ('audio_progress_50', 'analytics_event_audio_progress_50'), ('tafsir_open', 'analytics_event_tafsir_open'), ('word_meanings_open', 'analytics_event_word_meanings_open'), ('session_active', 'analytics_event_session_active'), ('recitation_correction', 'analytics_event_recitation_correction'), ('daily_wird_open', 'analytics_event_daily_wird_open'), ('language_change', 'analytics_event_language_change'), ('translation_text_view', 'analytics_event_translation_text_view'), ('translation_audio_play', 'analytics_event_translation_audio_play'), ('translation_lang_change', 'analytics_event_translation_lang_change'), ('client_error', 'analytics_event_client_error'), ('audio_error', 'analytics_event_audio_error'), ('api_error', 'analytics_event_api_error'), ('page_load_error', 'analytics_event_page_load_error'), ('screen_view', 'analytics_event_screen_view'), ('media_play', 'analytics_event_media_play'), ('media_error', 'analytics_event_media_error'), ('mobile_event', 'analytics_event_mobile_event')], max_length=50)),
                ('source_platform', models.CharField(blank=True, default='web', max_length=16)),
                ('path', models.CharField(max_length=255)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('surah_number', models.PositiveIntegerField(blank=True, null=True)),
                ('ayah_number', models.PositiveIntegerField(blank=True, null=True)),
                ('qari', models.CharField(blank=True, max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.analyticsvisitor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_i_event_t_011c8c_idx'), models.Index(fields=['path', 'created_at'], name='analytics_i_path_dfe87a_idx'), models.Index(fields=['source_platform', 'created_at'], name='analytics_i_source__238657_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('full_path', models.CharField(blank=True, max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('referrer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='analytics.analyticsvisitor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', 'created_at'], name='analytics_p_path_53ae0e_idx'), models.Index(fields=['created_at'], name='analytics_p_created_4c2b45_idx')],
            },
        ),
    ]
