# Generated by Django 5.2.8 on 2026-04-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagebroadcast",
            name="level",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="messagedelivery",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagedelivery",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
