# Generated by Django 5.2.8 on 2026-04-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="interactionevent",
            new_name="analytics_i_event_t_011c8c_idx",
            old_name="analytics_i_event_t_e601d8_idx",
        ),
        migrations.RenameIndex(
            model_name="interactionevent",
            new_name="analytics_i_path_dfe87a_idx",
            old_name="analytics_i_path_a_3d5b9b_idx",
        ),
        migrations.RenameIndex(
            model_name="pageview",
            new_name="analytics_p_path_53ae0e_idx",
            old_name="analytics_p_path_8c989f_idx",
        ),
        migrations.RenameIndex(
            model_name="pageview",
            new_name="analytics_p_created_4c2b45_idx",
            old_name="analytics_p_create_8cc7fa_idx",
        ),
    ]
