# Generated by ChatGPT Codex

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_rename_analytics_i_event_t_e601d8_idx_analytics_i_event_t_011c8c_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsIPAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("hits_count", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["-last_seen_at"]},
        ),
        migrations.AddField(
            model_name="analyticsvisitor",
            name="os_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="analyticsvisitor",
            name="total_active_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analyticsvisitor",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="interactionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("page_flip", "Page Flip"),
                    ("audio_play", "Audio Play"),
                    ("audio_complete", "Audio Complete"),
                    ("tafsir_open", "Tafsir Open"),
                    ("word_meanings_open", "Word Meanings Open"),
                    ("session_active", "Session Active"),
                ],
                max_length=50,
            ),
        ),
    ]
