# Generated by ChatGPT Codex

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_analyticsipaddress_visitor_user_os_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsvisitor",
            name="browser_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="analyticsvisitor",
            name="browser_version",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="analyticsvisitor",
            name="device_type",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="analyticsvisitor",
            name="os_version",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
