# Generated by ChatGPT Codex

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_visitor_os_browser_device_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsipaddress",
            name="country_code",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="analyticsipaddress",
            name="country_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="analyticsipaddress",
            name="last_language",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="analyticsvisitor",
            name="last_language",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="interactionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("page_flip", "Page Flip"),
                    ("audio_play", "Audio Play"),
                    ("audio_complete", "Audio Complete"),
                    ("tafsir_open", "Tafsir Open"),
                    ("word_meanings_open", "Word Meanings Open"),
                    ("session_active", "Session Active"),
                    ("recitation_correction", "Recitation Correction"),
                    ("daily_wird_open", "Daily Wird Open"),
                    ("language_change", "Language Change"),
                ],
                max_length=50,
            ),
        ),
    ]
