# Generated by ChatGPT

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_ip_country_language_and_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("page_flip", "Page Flip"),
                    ("audio_play", "Audio Play"),
                    ("audio_complete", "Audio Complete"),
                    ("audio_pause", "Audio Pause"),
                    ("audio_progress_50", "Audio Progress 50%"),
                    ("tafsir_open", "Tafsir Open"),
                    ("word_meanings_open", "Word Meanings Open"),
                    ("session_active", "Session Active"),
                    ("recitation_correction", "Recitation Correction"),
                    ("daily_wird_open", "Daily Wird Open"),
                    ("language_change", "Language Change"),
                ],
                max_length=50,
            ),
        ),
    ]
