# Generated by Django 5.2.8 on 2026-04-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[("in_app", "داخل النظام")], default="in_app", max_length=20
            ),
        ),
    ]
