# Generated by Django 5.2.14 on 2026-07-13 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0013_decimal_minutes_charged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'متاح'), ('reserved', 'محجوز'), ('blocked', 'محظور'), ('cancelled', 'ملغى'), ('expired', 'منتهي')], db_index=True, default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فترة متاحة',
                'verbose_name_plural': 'الفترات المتاحة',
                'ordering': ['start_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('new_memorization', 'حفظ جديد'), ('recitation', 'تسميع'), ('near_revision', 'مراجعة قريبة'), ('cumulative_revision', 'مراجعة شاملة'), ('recitation_correction', 'تصحيح تلاوة'), ('memorization_test', 'اختبار حفظ'), ('plan_follow_up', 'متابعة خطة الحفظ'), ('introductory_session', 'جلسة تعريفية'), ('other', 'أخرى')], max_length=40)),
                ('session_type_other', models.CharField(blank=True, default='', max_length=120)),
                ('student_notes', models.CharField(blank=True, default='', max_length=500)),
                ('teacher_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending_approval', 'بانتظار موافقة المعلم'), ('confirmed', 'مؤكد'), ('in_progress', 'جارٍ'), ('completed', 'مكتمل'), ('cancelled_by_student', 'ألغاه الطالب'), ('cancelled_by_teacher', 'ألغاه المعلم'), ('rejected_by_teacher', 'رفضه المعلم'), ('no_show_student', 'غياب الطالب'), ('no_show_teacher', 'غياب المعلم'), ('expired', 'فائت')], db_index=True, default='confirmed', max_length=32)),
                ('booked_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_24h_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_1h_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_10m_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='calls.callsession')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_cancelled', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_teacher', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.appointmentslot')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'ordering': ['-booked_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=32)),
                ('new_status', models.CharField(max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='appointments.appointment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل حالة موعد',
                'verbose_name_plural': 'سجلات حالات المواعيد',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Inclusive end date; null means open-ended within generation window.', null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurrence_type', models.CharField(choices=[('none', 'بدون تكرار'), ('daily', 'يوميًا'), ('weekly', 'أسبوعيًا'), ('weekly_selected', 'أيام محددة من الأسبوع'), ('biweekly', 'كل أسبوعين'), ('monthly', 'شهريًا')], default='none', max_length=32)),
                ('recurrence_interval', models.PositiveSmallIntegerField(default=1)),
                ('recurrence_days', models.JSONField(blank=True, default=list)),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('break_minutes', models.PositiveSmallIntegerField(default=5)),
                ('session_types', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قاعدة توفر',
                'verbose_name_plural': 'قواعد التوفر',
                'ordering': ['start_date', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('exception_type', models.CharField(choices=[('closed_day', 'إغلاق يوم كامل'), ('closed_range', 'إغلاق فترة'), ('cancel_occurrence', 'إلغاء تكرار واحد'), ('add_slots', 'إضافة وقت استثنائي')], max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to=settings.AUTH_USER_MODEL)),
                ('source_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='appointments.availabilityrule')),
            ],
            options={
                'verbose_name': 'استثناء توفر',
                'verbose_name_plural': 'استثناءات التوفر',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='source_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='appointments.availabilityrule'),
        ),
        migrations.CreateModel(
            name='TeacherBookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_enabled', models.BooleanField(default=True, verbose_name='استقبال الحجوزات')),
                ('approval_required', models.BooleanField(default=False, help_text='Reserved for future use; v1 always confirms immediately.', verbose_name='يتطلب موافقة المعلم')),
                ('default_slot_duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('default_break_minutes', models.PositiveSmallIntegerField(default=5)),
                ('minimum_booking_notice_minutes', models.PositiveIntegerField(default=60)),
                ('maximum_booking_window_days', models.PositiveSmallIntegerField(default=90)),
                ('cancellation_deadline_minutes', models.PositiveIntegerField(default=120, help_text='Student may cancel until this many minutes before start.')),
                ('max_active_bookings_per_student', models.PositiveSmallIntegerField(blank=True, help_text='Null means unlimited upcoming active bookings with this teacher.', null=True)),
                ('allowed_session_types', models.JSONField(blank=True, default=list)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_settings', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'إعدادات حجز المعلم',
                'verbose_name_plural': 'إعدادات حجز المعلمين',
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['teacher', 'status', 'booked_at'], name='appt_teacher_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['student', 'status', 'booked_at'], name='appt_student_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_approval', 'confirmed', 'in_progress'])), fields=('slot',), name='uniq_active_appointment_per_slot'),
        ),
        migrations.AddIndex(
            model_name='availabilityrule',
            index=models.Index(fields=['teacher', 'is_active', 'start_date'], name='appt_rule_teacher_active_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityexception',
            index=models.Index(fields=['teacher', 'date'], name='appt_exc_teacher_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['teacher', 'status', 'start_at'], name='appt_slot_teacher_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['start_at', 'end_at'], name='appt_slot_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.UniqueConstraint(fields=('teacher', 'start_at', 'end_at'), name='uniq_appt_slot_teacher_start_end'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='appt_slot_end_after_start'),
        ),
    ]
