# Generated by Django 5.2.14 on 2026-05-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_systemauthsettings_allow_api_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date of birth (تاريخ الميلاد)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enrollment_track',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enrollment track index 0–4 from mobile register step 2', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID (رقم الهوية); mobile may use username until sent explicitly', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, help_text='Educational qualification (المؤهل الدراسي)', max_length=255),
        ),
    ]
