# Generated by Django 5.2.14 on 2026-05-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_birth_date_user_enrollment_track_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(default=3, help_text='1=admin, 3=supervisor, 5=teacher, 9=student'),
        ),
    ]
