# Generated by Django 5.2.14 on 2026-06-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_type_rbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, help_text='Firebase Authentication UID for Google/mobile sign-in', max_length=128, null=True, unique=True),
        ),
    ]
