# Generated by Django 5.2.14 on 2026-06-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_firebase_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRegistrationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('verification_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', '-created_at'], name='accounts_em_email_dbcf2f_idx')],
            },
        ),
    ]
