# Generated by Django 5.2.14 on 2026-06-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_registration_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile photo', null=True, upload_to='profile_images/'),
        ),
    ]
