# Generated by Django 5.2.8 on 2026-04-05 06:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="البريد الإلكتروني"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_confirmed",
                    models.BooleanField(default=True, verbose_name="تم التأكيد"),
                ),
                (
                    "unsubscribe_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الاشتراك"
                    ),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ إلغاء الاشتراك"
                    ),
                ),
            ],
            options={
                "verbose_name": "مشترك نشرة بريدية",
                "verbose_name_plural": "مشتركو النشرة البريدية",
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
