# Generated by Django 5.2.14 on 2026-05-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='اسم الباقة')),
                ('duration_months', models.PositiveSmallIntegerField(verbose_name='المدة بالأشهر')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'باقة اشتراك',
                'verbose_name_plural': 'باقات الاشتراك',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
