# Generated by Django 5.2.14 on 2026-05-30 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(max_length=255, verbose_name='اسم الباقة')),
                ('duration_months', models.PositiveIntegerField(verbose_name='مدة الاشتراك بالأشهر')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('payment_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('payment_method', models.CharField(blank=True, default='', max_length=64)),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_subscriptions', to='subscription.subscriptionplan', verbose_name='الباقة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اشتراك طالب',
                'verbose_name_plural': 'سجل اشتراكات الطلاب',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
