# Generated by Django 5.2.14 on 2026-07-19 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_studentsubscription_transaction_reference_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteCreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(blank=True, default='', max_length=255)),
                ('purchased_minutes', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الدقائق المشتراة')),
                ('remaining_minutes', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الدقائق المتبقية')),
                ('purchased_at', models.DateTimeField(verbose_name='وقت الشراء')),
                ('expires_at', models.DateField(blank=True, help_text='null = باقة مفتوحة بلا انتهاء زمني', null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('store', models.CharField(blank=True, default='', max_length=32, verbose_name='المتجر')),
                ('store_product_id', models.CharField(blank=True, default='', max_length=255)),
                ('store_transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=512, verbose_name='معرّف عملية المتجر')),
                ('purchase_token', models.TextField(blank=True, default='', verbose_name='رمز/توقيع الشراء')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('exhausted', 'نفدت'), ('expired', 'منتهية')], db_index=True, default='active', max_length=20)),
                ('google_consume_pending', models.BooleanField(default=False, verbose_name='بانتظار consume في Google')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minute_credit_packs', to='subscription.subscriptionplan', verbose_name='الباقة')),
                ('student_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_packs', to='subscription.studentsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_credit_packs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حزمة رصيد دقائق',
                'verbose_name_plural': 'حزم رصيد الدقائق',
                'ordering': ['expires_at', 'purchased_at', 'id'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_6d0849_idx'), models.Index(fields=['user', 'expires_at'], name='subscriptio_user_id_195afc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('store_transaction_id', ''), _negated=True), fields=('store_transaction_id',), name='uniq_minute_pack_store_transaction_id')],
            },
        ),
    ]
