# Generated by Django 5.2.8 on 2026-04-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0002_alter_ayahposition_ayah_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qurra",
            options={},
        ),
        migrations.RemoveField(
            model_name="qurra",
            name="fullname",
        ),
        migrations.RemoveField(
            model_name="qurra",
            name="info",
        ),
        migrations.RemoveField(
            model_name="qurra",
            name="number",
        ),
        migrations.AlterField(
            model_name="qurra",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
