# Generated by Django 5.2.8 on 2026-05-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0009_audiolistenevent"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="audiolistenevent",
            new_name="quran_audio_created_851cef_idx",
            old_name="quran_audio_created_9d07a0_idx",
        ),
        migrations.RenameIndex(
            model_name="audiolistenevent",
            new_name="quran_audio_qari_co_c12626_idx",
            old_name="quran_audio_qari_co_9f8f0c_idx",
        ),
        migrations.RenameIndex(
            model_name="audiolistenevent",
            new_name="quran_audio_mushaf__cf03e1_idx",
            old_name="quran_audio_mushaf__07a71d_idx",
        ),
        migrations.RenameIndex(
            model_name="audiolistenevent",
            new_name="quran_audio_surah_n_49f363_idx",
            old_name="quran_audio_surah_n_6a4f77_idx",
        ),
    ]
