# Generated by Django 5.2.14 on 2026-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0012_qurra_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatmaprogress',
            name='tracking_mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='khatmaprogress',
            name='wird_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='khatmaprogress',
            name='current_wird_end_page',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='khatmaprogress',
            name='daily_amount_type',
            field=models.CharField(choices=[('rub3', 'ربع'), ('2rub3', 'ربعان'), ('3rub3', '3 أرباع'), ('hizb', 'حزب'), ('5rub3', '5 أرباع'), ('6rub3', '6 أرباع'), ('7rub3', '7 أرباع'), ('juz', 'جزء'), ('2juz', 'جزءان'), ('3juz', '3 أجزاء'), ('4juz', '4 أجزاء'), ('5juz', '5 أجزاء'), ('6juz', '6 أجزاء'), ('7juz', '7 أجزاء'), ('8juz', '8 أجزاء'), ('9juz', '9 أجزاء'), ('10juz', '10 أجزاء')], default='juz', max_length=10),
        ),
    ]
