# Generated by Django 5.2.14 on 2026-05-31 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'متاح'), ('busy', 'مشغول'), ('offline', 'غير متصل')], default='offline', max_length=10, verbose_name='الحالة')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availability', to=settings.AUTH_USER_MODEL, verbose_name='المعلّم')),
            ],
            options={
                'verbose_name': 'حالة المعلّم',
                'verbose_name_plural': 'حالات المعلّمين',
            },
        ),
    ]
