# Generated by Django 5.2.14 on 2026-06-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraa', '0004_registration_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='riwayat',
            field=models.TextField(blank=True, help_text='Quranic recitation tradition (الرواية)'),
        ),
    ]
